CREATE TABLE [dbo].[Utilisateur]
(
	[Utilisateur_Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Email] NVARCHAR (320) NOT NULL,
	[Password] VARBINARY (64) NOT NULL,
	[Pseudo] NVARCHAR (64) NOT NULL,
	[CreatedAt]  DATETIME2 NOT NULL DEFAULT GETDATE(),
    [DisabledAt] DATETIME2,
	CONSTRAINT UQ_Email UNIQUE ([Email]),
	CONSTRAINT UQ_Pseudo UNIQUE ([Pseudo]),
	CONSTRAINT PK_Utilisateur PRIMARY KEY ([Utilisateur_Id])
)
